version: "3.9"

services:
  app:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/vol/web
    depends_on:
      - db
    environment:
      - APP_ENV=production

  nginx:
    build:
      context: ./nginx
    restart: always
    depends_on:
      - app
    ports:
      - "8000:8000"
    volumes:
      - static-data:/vol/static

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=product
      - POSTGRES_USER=pro
      - POSTGRES_PASSWORD=pro123

volumes:
  static-data:
  postgres-data: