version: "3.9"

services:

  db:
    image: postgres:14.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=dp
      - POSTGRES_USER=dp
      - POSTGRES_PASSWORD=dp123
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  rabbitmq:
    image: "rabbitmq:alpine"

    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  redis:
    image: redis:7
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: "ps_pass" 
    ports:
      - "5050:80"

volumes:
    postgres-data:
    redis-data:

