# Generated by Django 4.0.7 on 2023-11-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
    ]
