# Generated by Django 4.0.7 on 2023-07-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_remove_file_file_height_remove_file_file_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='file_width',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
