# Generated by Django 4.0.7 on 2023-07-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
