# Generated by Django 4.0.7 on 2023-07-01 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('blog', '0003_post_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.file'),
        ),
    ]
