# Generated by Django 4.0.7 on 2023-07-01 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_image_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_id',
            new_name='image',
        ),
    ]
